### ISSUE TITLE
update Please ,Ur I am not receive Api From ur web

### ISSUE THREAD

**Issue by Stakingsoup** [vitaminarts/Telegram-scraper-api#1]

**Comment by seyedvahidtaheri** [comment]
Hi , did you get your api key ? it send to your email , check the
spam folder.

**Comment by vitaminarts** [comment]
> _No description provided._

Hi , did you get your api key ? it send to your email , check the
spam folder.

**Comment by kingsalman99** [comment]
no 
![Screenshot_2020-08-03-00-18-49-00](https://user-images.githubusercontent.com/58569784/89128294-fd157b00-d51e-11ea-83d2-dd51de3f1f4a.jpg)

**Comment by kingsalman99** [comment]
ur smtp error sir

**Comment by kingsalman99** [comment]
Bro What The command ,?? I want to Scrape content or message From a Telegram Channel. ?

**Comment by vitaminarts** [comment]
> ur smtp error sir

What's your email address ? i want to send your api key to your email again

**Comment by kingsalman99** [comment]
bellasapphire1933@gmail.com

**Comment by vitaminarts** [comment]
> [bellasapphire1933@gmail.com](mailto:bellasapphire1933@gmail.com)

Ok , i send it

**Comment by vitaminarts** [comment]
> Bro What The command ,?? I want to Scrape content or message From a Telegram Channel. ?

fill the key and channel and post parameters 

https://apibot.ir/getContents?key=&channel=&post=
