### ISSUE TITLE
راه ارتباطی

### ISSUE THREAD

**Issue by sirousjj** [vitaminarts/Telegram-scraper-api#4]
سلام.
وقت بخیر
سید یه راه ارتباطی به ما معرفی کن.
نه ایمیل های سایتت جواب میده
نه جی میل ات درسته. نه دایرکت اینتسا جواب میدین.
نه پشتیبانی سایتت جواب میده. 
همه راه ها به بن بسته.
من پروژه ام رو زمین مونده نیاز شدید به سرویس شما دارم. میخوام اشتراک تهیه کنم، ولی مشکل دارم.
هرچی ایمیل ارسال میکنم، خطای گیرنده میده که این آدرس ایمیل وجود ندارد.
لطفا یه راه ارتباطی درست درمون بهمون معرفی کن.
که من بتونم باهات یه ارتباط بگیرم.
ایمیل من :as.moini@gmail.com

ممنون میشم بهم یه ایمیل بدی.یا همینجا یه آدرس ایمیل ریپلای کن که من بتونم باهات در ارتباط باشم. 
سپاس فراوان

**Comment by vitaminarts** [comment]
سلام بزرگوار ایمیل رو به زودی بررسی می کنم.
apibotir@gmail.com
